nginx:
    restart: always
    container_name: my_nginx
    build: ./myNginx
    links:
        - webrtc_app_1:webrtc_app_1
        - webrtc_app_2:webrtc_app_2
    ports:
        - "80:80"

webrtc_app_1:
    restart: always
    container_name: my_webrtc_app_1
    build: ./prjRTCBroadcast
    env_file:
        - ./.keys.env
    ports: 
        - "8080"

webrtc_app_2:
    restart: always
    container_name: my_webrtc_app_2
    build: ./prjRTCBroadcast
    env_file:
        - ./.keys.env
    ports: 
        - "8080"
