nginx:
    build: ../myNginx
    links:
        - node_1:node_1
        - node_2:node_2
        - node_3:node_3
    ports:
        - "80:80"

node_1:
    build: .
    env_file:
        - ./.keys.env
    ports: 
        - "8080"

node_2:
    build: .
    env_file:
        - ./.keys.env
    ports: 
        - "8080"

node_3:
    build: .
    env_file:
        - ./.keys.env
    ports: 
        - "8080"